### ISSUE TITLE
Hexo server failure on `Assests.addAbsoluteFilePath`

### ISSUE THREAD

**Issue by thebearjew** [meteor/docs#56]
I've been having an issue running the documentation locally after running `git submodule update --init`, `npm install`, and `npm start` on meteor/docs branch `master`.

Hexo is failing due to  error:

```
API Data not found: Assets.absoluteFilePath
```

---

The full error message:

```
> hexo server

INFO  Start processing
API Data not found: Assets.absoluteFilePath
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  TypeError: Cannot read property 'replace' of undefined
    at Object.exports.prettifyError (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/nunjucks/src/lib.js:34:15)
    at /Users/CASE/Documents/JYProgramming/other/docs/node_modules/nunjucks/src/environment.js:485:31
    at root [as rootRenderFunc] (eval at <anonymous> (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:22:3)
    at Obj.extend.render (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/nunjucks/src/environment.js:478:15)
    at Obj.extend.renderString (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/nunjucks/src/environment.js:326:21)
    at /Users/CASE/Documents/JYProgramming/other/docs/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/bluebird/js/release/promise.js:77:14)
    at Tag.render (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/CASE/Documents/JYProgramming/other/docs/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/bluebird/js/release/promise.js:685:18)
FATAL (unknown path)
  TypeError: Cannot read property 'replace' of undefined
Template render error: (unknown path)
  TypeError: Cannot read property 'replace' of undefined
    at Object.exports.prettifyError (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/nunjucks/src/lib.js:34:15)
    at /Users/CASE/Documents/JYProgramming/other/docs/node_modules/nunjucks/src/environment.js:485:31
    at root [as rootRenderFunc] (eval at <anonymous> (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:22:3)
    at Obj.extend.render (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/nunjucks/src/environment.js:478:15)
    at Obj.extend.renderString (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/nunjucks/src/environment.js:326:21)
    at /Users/CASE/Documents/JYProgramming/other/docs/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/bluebird/js/release/promise.js:77:14)
    at Tag.render (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/CASE/Documents/JYProgramming/other/docs/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/CASE/Documents/JYProgramming/other/docs/node_modules/bluebird/js/release/promise.js:685:18)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.0.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! hexo-site@0.0.0 start: `hexo server`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the hexo-site@0.0.0 start script 'hexo server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hexo-site package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     hexo server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hexo-site
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hexo-site
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/CASE/Documents/JYProgramming/other/docs/npm-debug.log
```

**Comment by thebearjew** [comment]
I'll also add that the same error exists when running on branch `version-NEXT`

**Comment by tmeasday** [comment]
@thebearjew it works for me on `master`. Did you get another error earlier about jsdoc failing? 

My `code` submodule is at 008b0eb6cdd52bcfd97490b582782ebe2490dfe1.

**Comment by tmeasday** [comment]
(I'm going to update master now for 1.3.4 though)

**Comment by tmeasday** [comment]
@thebearjew I'm guessing amongst everything updating to 1.3.4 and merging `version-NEXT`, your issue is solved. Ping me if not.
